site_name: PAMPAS
nav:
  - Home: index.md
  - Get started:
    - First steps: first-steps.md
  - Software modules:
      - Overview: software-overview.md
  - Hardware modules:
      - Overview: hardware-overview.md
theme:
  name: material
  features:
    - navigation.sections   # top-level sections render as plain headers, not clickable/collapsible
    - navigation.expand     # all sections start expanded
extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format