site_name: PAMPAS
nav:
  - Home: index.md
  - Software modules:
      - Overview: software-overview.md
  - Hardware modules:
      - Overview: hardware-overview.md
  - Trainee section:
    - Onboarding: trainee-section/onboarding.md
    - Challenge: trainee-section/challenge.md
theme:
  name: material
  features:
    - navigation.sections   # top-level sections render as plain headers, not clickable/collapsible
    - navigation.expand     # all sections start expanded
extra:
  version:
    provider: mike
