name: Autodeploy docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Build and deploy docs
        run: uv run --no-project --with mkdocs-material -- mkdocs gh-deploy --force
